name: send-email

on:
  schedule:
    # 13:15 UTC is 7:15 AM Mountain Time (MDT, UTC-6)
    - cron: '15 13 * * 1-5'
  workflow_dispatch:

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Export Secrets
        run: |
          echo "NEWSAPI_KEY=${{ secrets.NEWSAPI_KEY }}" >> $GITHUB_ENV
          echo "GMAIL_USER=${{ secrets.GMAIL_USER }}" >> $GITHUB_ENV
          echo "GMAIL_APP_PASSWORD=${{ secrets.GMAIL_APP_PASSWORD }}" >> $GITHUB_ENV
          echo "RECIPIENT_EMAIL=${{ secrets.RECIPIENT_EMAIL }}" >> $GITHUB_ENV

      - name: Run Script
        run: python main.py
